# ~/.config/alacritty/alacritty.toml
#[font]
#size = 14.0
#normal = { family = "FiraCode Nerd Font", style = "Regular" }
#bold = { family = "FiraCode Nerd Font", style = "Bold" }
#italic = { family = "FiraCode Nerd Font", style = "Italic" }
#
#[window]
#opacity = 0.9
#
#[colors]
#primary = { background = "#1a1b26", foreground = "#a9b1d6" }

[font]
size = 14.0
normal = { family = "JetBrainsMono Nerd Font Mono", style = "Regular" }
bold = { family = "JetBrainsMono Nerd Font Mono", style = "Bold" }
italic = { family = "JetBrainsMono Nerd Font Mono", style = "Italic" }

[window]
opacity = 0.7

[colors]
primary = { background = "#1a1b26", foreground = "#a9b1d6" }

